# config/routes.yaml
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_login:
    path: /
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
   

liste_categories:
    path: /categories
    controller: App\Controller\ListeCategoriesController::listeCategories
    methods: ['GET']

lister_licencies_par_categorie:
    path: /categorie/{categorieId}/licencies
    controller: App\Controller\ListeLicencieCategorieController::listerLicenciesParCategorie
    methods: ['GET']


lister_contacts_par_categorie:
    path: '/categorie/{categorieId}/contacts'
    controller: 'App\Controller\ListeContactCategorieController::listerContactsParCategorie'
    methods: ['GET']
    requirements:
        categorieId: '\d+' 

# config/routes.yaml

list_mail:
    path: '/list/mail'
    controller: 'App\Controller\MailController::viewMail'
    methods: ['GET']

# config/routes.yaml
mail_contacts_educateurs:
    path: /mail/contacts/educateurs
    controller: App\Controller\MailContactsEducateursController::index

app_send_mail_contact:
    path: /mail/contact/send
    controller: App\Controller\MailContactsEducateursController::add



